### PR TITLE
Update for GRASS GIS 7.9.dev

### PR DESCRIPTION
**Pull request by nilason**
With this it should compile with mac!

### CODE REVIEW

**Comment by nilason** [comment]
[CI results](https://github.com/nilason/grass-gis-experimental-ci/actions/runs/185608617)

**Comment by wenzeslaus** [comment]
The CI looks good. If this works, the next question is if this should become the test which is running on OSGeo/grass.

**Comment by wenzeslaus** [comment]
The build on the branch after merge fails with things like:

```
checking for socket... no
configure: warning: *** Unable to locate socket() function.
checking for socket in -lsocket... no
checking for location of zlib includes... 
configure: error: *** Unable to locate zlib includes.
checking for zlib.h... no
...
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _main in conftest-12a449.o
ld: symbol(s) not found for architecture x86_64
 configure:4983:10: fatal error: 'assert.h' file not found
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
./configure: line 5253: /lib/cpp: No such file or directory
```

Although this repo lacks run on pull_request in GH Actions, I'm don't what would be the difference with your branch.

**Comment by neteler** [comment]
Shouldn't there be added a zlib-dev package (whatever the precise name is) etc in https://github.com/nilason/grass-gis-experimental-ci/blob/cf028d8ea099c512bf47a1c47056dd6f363f2480/environment.yml 
?

**Comment by nilason** [comment]
> Shouldn't there be added a zlib-dev package (whatever the precise name is) etc in https://github.com/nilason/grass-gis-experimental-ci/blob/cf028d8ea099c512bf47a1c47056dd6f363f2480/environment.yml
> ?

No, that file is ok. Just pushed a new PR #3 that will (now hopefully :-) fix this.

**Pull request merged**
